services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: super
      MYSQL_DATABASE: fingerprint_system
      MYSQL_USER: common
      MYSQL_PASSWORD: common
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - ./my-db/setup.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    networks:
      - app-network
#####################################################
# PHPMYADMIN (MySQL)
#####################################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data: {}
networks:
  app-network:
    driver: bridge
