version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./my-db/data:/var/lib/mysql
      - ./my-db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./my-db/conf:/etc/mysql/conf.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_PORT=3306
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
